### ISSUE TITLE
crayfish plugin doesnt work in qgis 3.20 (windows)

### ISSUE THREAD

**Issue by Maiyourathaan** [lutraconsulting/qgis-crayfish-plugin#482]
I have installed QGIS 3.20 in my computer and wanted to use crayfish plugin for Mesh analysis. When I install the plugin it shows the following error and the plugin does not appearing in the toolbox window.

Couldn't load plugin 'crayfish' due to an error when calling its classFactory() method
```
AttributeError: module 'time' has no attribute 'clock'
Traceback (most recent call last):
File "C:\AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_widget.py", line 38, in
import pyqtgraph
File "C:\PROGRA1/QGIS321.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'
```

**Comment by vcloarec** [comment]
Hello,
which version of  Crayfish?
can you update?

**Comment by Maiyourathaan** [comment]
i have installed the Crayfish Version of 3.5.2 and also try with the version 3.4.6, non of them are working in QGIS 3.20 either in Long Term release 3.16.10.
I can use Crayfish version 3.4.6 only in QGIS 3.16.4, and  new version of it (3.5.2) does not working in this old QGIS (3.4.6) version (well this is another question, why new crayfish does not work in old QGIS version).

**Comment by PeterPetrik** [comment]
How you installed QGIS? standalone/new installer/old osgeo installer?

**Comment by Maiyourathaan** [comment]
I installed it as a Standalone installers (MSI)

**Comment by vcloarec** [comment]
I am wondering if it is not link to https://lists.osgeo.org/pipermail/qgis-developer/2021-September/063967.html

**Comment by Maiyourathaan** [comment]
Do you have any solution for this problem?

**Comment by PeterPetrik** [comment]
working on it

**Comment by Maiyourathaan** [comment]
> 
> 
> working on it

Thanks

**Comment by PeterPetrik** [comment]
@Maiyourathaan can you please try if this works for you?
[crayfish.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/7142266/crayfish.zip)

**Comment by PeterPetrik** [comment]
released 3.5.3 https://plugins.qgis.org/plugins/crayfish/ 

please us new installer and qgis 3.20+
QGIS 3.16 is not supported by this version

**Comment by Maiyourathaan** [comment]
Thanks a lot it works
