### ISSUE TITLE
Crayfish does not work with QGIS 3.22.1 on linux

### ISSUE THREAD

**Issue by dketterer** [lutraconsulting/qgis-crayfish-plugin#484]
During the installation and activation I get this error:

```
Couldn't load plugin 'crayfish' due to an error when calling its classFactory() method 

ImportError: cannot import name 'sip' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py) 
Traceback (most recent call last):
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/plot_widget.py", line 38, in 
    import pyqtgraph
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/__init__.py", line 29, in classFactory
    from .plugin import CrayfishPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/plugin.py", line 31, in 
    from .gui.plot_widget import CrayfishPlotWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/plot_widget.py", line 40, in 
    import crayfish.pyqtgraph_0_12_2 as pyqtgraph
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/pyqtgraph_0_12_2/__init__.py", line 13, in 
    from .Qt import QtCore, QtGui, mkQApp
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/pyqtgraph_0_12_2/Qt/__init__.py", line 155, in 
    from PyQt5 import sip, uic
ImportError: cannot import name 'sip' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)


Python version: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0] 
QGIS version: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

Python Path:
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/extlibs
/usr/share/qgis/python
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/daniel/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/daniel/.local/share/QGIS/QGIS3/profiles/default/python
```

It may be related to the recent pyqtgraph [updates](https://github.com/lutraconsulting/qgis-crayfish-plugin/issues/482)

**Comment by saberraz** [comment]
Hi @dketterer 

Yes, you need to install  `python3-pyqtgraph` package to work.

**Comment by dketterer** [comment]
Wow, thank you for the quick response that worked!
